spring:
  datasource:
    url: jdbc:mysql://172.16.244.209:3306/open_class
    username: root
    password: yuluo
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false


server:
  port: 8888

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo